services:
  - type: web
    name: train-search-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: train-search-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://train-search-backend.onrender.com
